<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Investigate The Cold Storage Milk Quality Maintenance</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://lioneltayyd.github.io/site/">Lionel Tay</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="investigating_the_cold_storage_milk_quality_maintenance.html">Investigating The Cold Storage Milk Quality Maintenance</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Investigate The Cold Storage Milk Quality Maintenance</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#project-purpose.">Project purpose.</a></li>
<li><a href="#explore-and-familiarise-with-the-cold_storage_temp-dataset.">1 Explore and familiarise with the ‘Cold_Storage_Temp’ dataset.</a><ul>
<li><a href="#summarise-of-the-dataset.">1.1 Summarise of the dataset.</a></li>
<li><a href="#transform-dtype.">1.2 Transform dtype.</a></li>
<li><a href="#summarise-of-the-dataset-by-season-variable.">1.3 Summarise of the dataset by ‘Season’ variable.</a></li>
<li><a href="#check-the-detail-of-the-dataset.">1.4 Check the detail of the dataset.</a></li>
<li><a href="#visualise-the-density-distribution-for-temperature-variable.">1.5 Visualise the density distribution for ‘Temperature’ variable.</a></li>
<li><a href="#visualise-the-distribution-for-temperature-variable-by-season.">1.6 Visualise the distribution for ‘Temperature’ variable by ‘Season’.</a></li>
<li><a href="#visualise-the-density-distribution-for-temperature-variable-by-season.">1.7 Visualise the density distribution for ‘Temperature’ variable by ‘Season’.</a></li>
<li><a href="#summary-for-section-1">1.8 Summary for section 1:</a></li>
</ul></li>
<li><a href="#find-the-proportion-of-temperature-that-exceed-below-2c-and-above-4c.">2 Find the proportion of temperature that exceed below 2°C and above 4°C.</a></li>
<li><a href="#perform-one-way-anova-to-see-if-there-is-significant-difference-in-milk-temperature-between-different-seasons.">3 Perform One-way ANOVA to see if there is significant difference in milk temperature between different seasons.</a><ul>
<li><a href="#perform-an-assumption-test.">3.1 Perform an assumption test.</a></li>
<li><a href="#summary-for-section-3.1.">3.2 Summary for section 3.1.</a></li>
<li><a href="#perform-anova-test.">3.3 Perform ANOVA test.</a></li>
<li><a href="#summary-for-section-3.3.">3.4 Summary for section 3.3.</a></li>
</ul></li>
<li><a href="#conclusion.">4 Conclusion.</a></li>
<li><a href="#notes-for-future-reference.">5 Notes for future reference.</a></li>
</ul>
</div>

<hr />
<div id="project-purpose." class="section level2">
<h2>Project purpose.</h2>
<p>Cold Storage started its operations in Jan 2016. They are in the business of storing Pasteurized Fresh Whole or Skimmed Milk, Sweet Cream, Flavoured Milk Drinks. To ensure that there is no change of texture, body appearance, separation of fats the <strong>optimal temperature to be maintained is between 2—4°C</strong>.</p>
<p>In the first year of business, they outsourced the plant maintenance work to a professional company with stiff penalty clauses. It was agreed that if it was statistically proven that the probability of temperature going <strong>outside the 2—4°C</strong> during the one-year contract was <strong>above 2.5% and less than 5%</strong> then the <strong>penalty would be 10% of AMC (annual maintenance contract)</strong>. In case it <strong>exceeded 5%</strong> then the <strong>penalty would be 25% of the AMC fee</strong>.</p>
<p>The objective is to find proportion of milk temperature that exceed <strong>below 2°C</strong> or <strong>above 4°C</strong> and determine the penalty Cold Storage should impose based on the contract should the company exceed the limits.</p>
<hr />
</div>
<div id="explore-and-familiarise-with-the-cold_storage_temp-dataset." class="section level2">
<h2>1 Explore and familiarise with the ‘Cold_Storage_Temp’ dataset.</h2>
<pre class="r"><code>library(pacman)
p_load(readr, dplyr, plyr, ggplot2, car, sjstats, multcomp, nortest, pwr, reshape2)</code></pre>
<pre class="r"><code>CS.temp = read_csv(&quot;csv/Cold_Storage_Temp_Data.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Season = col_character(),
##   Month = col_character(),
##   Date = col_double(),
##   Temperature = col_double()
## )</code></pre>
<pre class="r"><code>CS.temp</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Season"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Month"],"name":[2],"type":["chr"],"align":["left"]},{"label":["Date"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Temperature"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"Winter","2":"Jan","3":"1","4":"2.3"},{"1":"Winter","2":"Jan","3":"2","4":"2.2"},{"1":"Winter","2":"Jan","3":"3","4":"2.4"},{"1":"Winter","2":"Jan","3":"4","4":"2.8"},{"1":"Winter","2":"Jan","3":"5","4":"2.5"},{"1":"Winter","2":"Jan","3":"6","4":"2.4"},{"1":"Winter","2":"Jan","3":"7","4":"2.8"},{"1":"Winter","2":"Jan","3":"8","4":"3.0"},{"1":"Winter","2":"Jan","3":"9","4":"2.4"},{"1":"Winter","2":"Jan","3":"10","4":"2.9"},{"1":"Winter","2":"Jan","3":"11","4":"2.4"},{"1":"Winter","2":"Jan","3":"12","4":"2.5"},{"1":"Winter","2":"Jan","3":"13","4":"2.6"},{"1":"Winter","2":"Jan","3":"14","4":"2.9"},{"1":"Winter","2":"Jan","3":"15","4":"3.4"},{"1":"Winter","2":"Jan","3":"16","4":"3.9"},{"1":"Winter","2":"Jan","3":"17","4":"3.3"},{"1":"Winter","2":"Jan","3":"18","4":"3.3"},{"1":"Winter","2":"Jan","3":"19","4":"2.8"},{"1":"Winter","2":"Jan","3":"20","4":"2.4"},{"1":"Winter","2":"Jan","3":"21","4":"2.7"},{"1":"Winter","2":"Jan","3":"22","4":"2.8"},{"1":"Winter","2":"Jan","3":"23","4":"2.7"},{"1":"Winter","2":"Jan","3":"24","4":"2.4"},{"1":"Winter","2":"Jan","3":"25","4":"3.5"},{"1":"Winter","2":"Jan","3":"26","4":"3.8"},{"1":"Winter","2":"Jan","3":"27","4":"2.6"},{"1":"Winter","2":"Jan","3":"28","4":"2.8"},{"1":"Winter","2":"Jan","3":"29","4":"3.1"},{"1":"Winter","2":"Jan","3":"30","4":"2.5"},{"1":"Winter","2":"Jan","3":"31","4":"2.4"},{"1":"Summer","2":"Feb","3":"1","4":"3.1"},{"1":"Summer","2":"Feb","3":"2","4":"3.3"},{"1":"Summer","2":"Feb","3":"3","4":"3.0"},{"1":"Summer","2":"Feb","3":"4","4":"3.9"},{"1":"Summer","2":"Feb","3":"5","4":"3.3"},{"1":"Summer","2":"Feb","3":"6","4":"3.1"},{"1":"Summer","2":"Feb","3":"7","4":"2.9"},{"1":"Summer","2":"Feb","3":"8","4":"2.9"},{"1":"Summer","2":"Feb","3":"9","4":"3.4"},{"1":"Summer","2":"Feb","3":"10","4":"3.0"},{"1":"Summer","2":"Feb","3":"11","4":"3.5"},{"1":"Summer","2":"Feb","3":"12","4":"3.2"},{"1":"Summer","2":"Feb","3":"13","4":"3.2"},{"1":"Summer","2":"Feb","3":"14","4":"3.7"},{"1":"Summer","2":"Feb","3":"15","4":"3.7"},{"1":"Summer","2":"Feb","3":"16","4":"3.4"},{"1":"Summer","2":"Feb","3":"17","4":"3.2"},{"1":"Summer","2":"Feb","3":"18","4":"2.6"},{"1":"Summer","2":"Feb","3":"19","4":"2.8"},{"1":"Summer","2":"Feb","3":"20","4":"3.1"},{"1":"Summer","2":"Feb","3":"21","4":"3.7"},{"1":"Summer","2":"Feb","3":"22","4":"3.5"},{"1":"Summer","2":"Feb","3":"23","4":"3.3"},{"1":"Summer","2":"Feb","3":"24","4":"3.2"},{"1":"Summer","2":"Feb","3":"25","4":"2.8"},{"1":"Summer","2":"Feb","3":"26","4":"2.9"},{"1":"Summer","2":"Feb","3":"27","4":"3.1"},{"1":"Summer","2":"Feb","3":"28","4":"3.0"},{"1":"Summer","2":"Mar","3":"1","4":"3.2"},{"1":"Summer","2":"Mar","3":"2","4":"2.7"},{"1":"Summer","2":"Mar","3":"3","4":"2.9"},{"1":"Summer","2":"Mar","3":"4","4":"3.6"},{"1":"Summer","2":"Mar","3":"5","4":"3.3"},{"1":"Summer","2":"Mar","3":"6","4":"3.2"},{"1":"Summer","2":"Mar","3":"7","4":"2.7"},{"1":"Summer","2":"Mar","3":"8","4":"3.0"},{"1":"Summer","2":"Mar","3":"9","4":"3.2"},{"1":"Summer","2":"Mar","3":"10","4":"2.6"},{"1":"Summer","2":"Mar","3":"11","4":"3.7"},{"1":"Summer","2":"Mar","3":"12","4":"3.1"},{"1":"Summer","2":"Mar","3":"13","4":"3.2"},{"1":"Summer","2":"Mar","3":"14","4":"3.0"},{"1":"Summer","2":"Mar","3":"15","4":"3.2"},{"1":"Summer","2":"Mar","3":"16","4":"2.7"},{"1":"Summer","2":"Mar","3":"17","4":"2.7"},{"1":"Summer","2":"Mar","3":"18","4":"2.9"},{"1":"Summer","2":"Mar","3":"19","4":"3.1"},{"1":"Summer","2":"Mar","3":"20","4":"3.3"},{"1":"Summer","2":"Mar","3":"21","4":"3.4"},{"1":"Summer","2":"Mar","3":"22","4":"2.5"},{"1":"Summer","2":"Mar","3":"23","4":"2.6"},{"1":"Summer","2":"Mar","3":"24","4":"3.1"},{"1":"Summer","2":"Mar","3":"25","4":"3.3"},{"1":"Summer","2":"Mar","3":"26","4":"3.4"},{"1":"Summer","2":"Mar","3":"27","4":"2.6"},{"1":"Summer","2":"Mar","3":"28","4":"3.5"},{"1":"Summer","2":"Mar","3":"29","4":"3.8"},{"1":"Summer","2":"Mar","3":"30","4":"3.4"},{"1":"Summer","2":"Mar","3":"31","4":"3.3"},{"1":"Summer","2":"Apr","3":"1","4":"2.6"},{"1":"Summer","2":"Apr","3":"2","4":"3.4"},{"1":"Summer","2":"Apr","3":"3","4":"3.4"},{"1":"Summer","2":"Apr","3":"4","4":"3.2"},{"1":"Summer","2":"Apr","3":"5","4":"3.0"},{"1":"Summer","2":"Apr","3":"6","4":"3.2"},{"1":"Summer","2":"Apr","3":"7","4":"3.0"},{"1":"Summer","2":"Apr","3":"8","4":"3.2"},{"1":"Summer","2":"Apr","3":"9","4":"3.2"},{"1":"Summer","2":"Apr","3":"10","4":"4.0"},{"1":"Summer","2":"Apr","3":"11","4":"4.0"},{"1":"Summer","2":"Apr","3":"12","4":"2.7"},{"1":"Summer","2":"Apr","3":"13","4":"3.7"},{"1":"Summer","2":"Apr","3":"14","4":"2.9"},{"1":"Summer","2":"Apr","3":"15","4":"3.1"},{"1":"Summer","2":"Apr","3":"16","4":"3.0"},{"1":"Summer","2":"Apr","3":"17","4":"3.6"},{"1":"Summer","2":"Apr","3":"18","4":"3.5"},{"1":"Summer","2":"Apr","3":"19","4":"2.6"},{"1":"Summer","2":"Apr","3":"20","4":"3.5"},{"1":"Summer","2":"Apr","3":"21","4":"2.6"},{"1":"Summer","2":"Apr","3":"22","4":"2.7"},{"1":"Summer","2":"Apr","3":"23","4":"2.9"},{"1":"Summer","2":"Apr","3":"24","4":"3.2"},{"1":"Summer","2":"Apr","3":"25","4":"3.2"},{"1":"Summer","2":"Apr","3":"26","4":"3.4"},{"1":"Summer","2":"Apr","3":"27","4":"2.6"},{"1":"Summer","2":"Apr","3":"28","4":"2.8"},{"1":"Summer","2":"Apr","3":"29","4":"3.0"},{"1":"Summer","2":"Apr","3":"30","4":"2.5"},{"1":"Summer","2":"May","3":"1","4":"2.6"},{"1":"Summer","2":"May","3":"2","4":"3.2"},{"1":"Summer","2":"May","3":"3","4":"2.8"},{"1":"Summer","2":"May","3":"4","4":"3.6"},{"1":"Summer","2":"May","3":"5","4":"3.1"},{"1":"Summer","2":"May","3":"6","4":"3.3"},{"1":"Summer","2":"May","3":"7","4":"3.2"},{"1":"Summer","2":"May","3":"8","4":"2.6"},{"1":"Summer","2":"May","3":"9","4":"3.3"},{"1":"Summer","2":"May","3":"10","4":"3.3"},{"1":"Summer","2":"May","3":"11","4":"2.7"},{"1":"Summer","2":"May","3":"12","4":"3.4"},{"1":"Summer","2":"May","3":"13","4":"3.0"},{"1":"Summer","2":"May","3":"14","4":"2.9"},{"1":"Summer","2":"May","3":"15","4":"2.9"},{"1":"Summer","2":"May","3":"16","4":"3.2"},{"1":"Summer","2":"May","3":"17","4":"3.6"},{"1":"Summer","2":"May","3":"18","4":"2.9"},{"1":"Summer","2":"May","3":"19","4":"3.4"},{"1":"Summer","2":"May","3":"20","4":"4.0"},{"1":"Summer","2":"May","3":"21","4":"3.6"},{"1":"Summer","2":"May","3":"22","4":"3.1"},{"1":"Summer","2":"May","3":"23","4":"3.1"},{"1":"Summer","2":"May","3":"24","4":"2.9"},{"1":"Summer","2":"May","3":"25","4":"3.2"},{"1":"Summer","2":"May","3":"26","4":"2.6"},{"1":"Summer","2":"May","3":"27","4":"2.9"},{"1":"Summer","2":"May","3":"28","4":"3.7"},{"1":"Summer","2":"May","3":"29","4":"3.5"},{"1":"Summer","2":"May","3":"30","4":"3.1"},{"1":"Summer","2":"May","3":"31","4":"3.3"},{"1":"Rainy","2":"Jun","3":"1","4":"3.4"},{"1":"Rainy","2":"Jun","3":"2","4":"3.4"},{"1":"Rainy","2":"Jun","3":"3","4":"2.9"},{"1":"Rainy","2":"Jun","3":"4","4":"3.1"},{"1":"Rainy","2":"Jun","3":"5","4":"2.8"},{"1":"Rainy","2":"Jun","3":"6","4":"2.9"},{"1":"Rainy","2":"Jun","3":"7","4":"3.8"},{"1":"Rainy","2":"Jun","3":"8","4":"2.7"},{"1":"Rainy","2":"Jun","3":"9","4":"3.5"},{"1":"Rainy","2":"Jun","3":"10","4":"3.5"},{"1":"Rainy","2":"Jun","3":"11","4":"2.8"},{"1":"Rainy","2":"Jun","3":"12","4":"2.9"},{"1":"Rainy","2":"Jun","3":"13","4":"3.0"},{"1":"Rainy","2":"Jun","3":"14","4":"2.7"},{"1":"Rainy","2":"Jun","3":"15","4":"2.6"},{"1":"Rainy","2":"Jun","3":"16","4":"2.5"},{"1":"Rainy","2":"Jun","3":"17","4":"2.3"},{"1":"Rainy","2":"Jun","3":"18","4":"2.7"},{"1":"Rainy","2":"Jun","3":"19","4":"3.9"},{"1":"Rainy","2":"Jun","3":"20","4":"2.8"},{"1":"Rainy","2":"Jun","3":"21","4":"3.1"},{"1":"Rainy","2":"Jun","3":"22","4":"3.3"},{"1":"Rainy","2":"Jun","3":"23","4":"2.1"},{"1":"Rainy","2":"Jun","3":"24","4":"2.8"},{"1":"Rainy","2":"Jun","3":"25","4":"3.6"},{"1":"Rainy","2":"Jun","3":"26","4":"3.3"},{"1":"Rainy","2":"Jun","3":"27","4":"3.0"},{"1":"Rainy","2":"Jun","3":"28","4":"3.8"},{"1":"Rainy","2":"Jun","3":"29","4":"2.9"},{"1":"Rainy","2":"Jun","3":"30","4":"2.7"},{"1":"Rainy","2":"Jul","3":"1","4":"3.1"},{"1":"Rainy","2":"Jul","3":"2","4":"2.7"},{"1":"Rainy","2":"Jul","3":"3","4":"2.5"},{"1":"Rainy","2":"Jul","3":"4","4":"2.7"},{"1":"Rainy","2":"Jul","3":"5","4":"3.4"},{"1":"Rainy","2":"Jul","3":"6","4":"2.5"},{"1":"Rainy","2":"Jul","3":"7","4":"2.9"},{"1":"Rainy","2":"Jul","3":"8","4":"2.8"},{"1":"Rainy","2":"Jul","3":"9","4":"3.7"},{"1":"Rainy","2":"Jul","3":"10","4":"4.2"},{"1":"Rainy","2":"Jul","3":"11","4":"3.2"},{"1":"Rainy","2":"Jul","3":"12","4":"2.9"},{"1":"Rainy","2":"Jul","3":"13","4":"3.9"},{"1":"Rainy","2":"Jul","3":"14","4":"3.3"},{"1":"Rainy","2":"Jul","3":"15","4":"3.3"},{"1":"Rainy","2":"Jul","3":"16","4":"3.2"},{"1":"Rainy","2":"Jul","3":"17","4":"3.5"},{"1":"Rainy","2":"Jul","3":"18","4":"2.8"},{"1":"Rainy","2":"Jul","3":"19","4":"3.0"},{"1":"Rainy","2":"Jul","3":"20","4":"2.7"},{"1":"Rainy","2":"Jul","3":"21","4":"2.9"},{"1":"Rainy","2":"Jul","3":"22","4":"2.5"},{"1":"Rainy","2":"Jul","3":"23","4":"1.9"},{"1":"Rainy","2":"Jul","3":"24","4":"3.2"},{"1":"Rainy","2":"Jul","3":"25","4":"3.1"},{"1":"Rainy","2":"Jul","3":"26","4":"2.3"},{"1":"Rainy","2":"Jul","3":"27","4":"2.5"},{"1":"Rainy","2":"Jul","3":"28","4":"3.8"},{"1":"Rainy","2":"Jul","3":"29","4":"3.2"},{"1":"Rainy","2":"Jul","3":"30","4":"2.8"},{"1":"Rainy","2":"Jul","3":"31","4":"3.1"},{"1":"Rainy","2":"Aug","3":"1","4":"3.4"},{"1":"Rainy","2":"Aug","3":"2","4":"3.3"},{"1":"Rainy","2":"Aug","3":"3","4":"3.4"},{"1":"Rainy","2":"Aug","3":"4","4":"3.6"},{"1":"Rainy","2":"Aug","3":"5","4":"2.9"},{"1":"Rainy","2":"Aug","3":"6","4":"3.2"},{"1":"Rainy","2":"Aug","3":"7","4":"2.7"},{"1":"Rainy","2":"Aug","3":"8","4":"2.4"},{"1":"Rainy","2":"Aug","3":"9","4":"3.0"},{"1":"Rainy","2":"Aug","3":"10","4":"2.3"},{"1":"Rainy","2":"Aug","3":"11","4":"3.5"},{"1":"Rainy","2":"Aug","3":"12","4":"2.9"},{"1":"Rainy","2":"Aug","3":"13","4":"3.7"},{"1":"Rainy","2":"Aug","3":"14","4":"3.4"},{"1":"Rainy","2":"Aug","3":"15","4":"3.8"},{"1":"Rainy","2":"Aug","3":"16","4":"2.4"},{"1":"Rainy","2":"Aug","3":"17","4":"2.8"},{"1":"Rainy","2":"Aug","3":"18","4":"3.1"},{"1":"Rainy","2":"Aug","3":"19","4":"3.0"},{"1":"Rainy","2":"Aug","3":"20","4":"2.9"},{"1":"Rainy","2":"Aug","3":"21","4":"3.4"},{"1":"Rainy","2":"Aug","3":"22","4":"4.3"},{"1":"Rainy","2":"Aug","3":"23","4":"2.5"},{"1":"Rainy","2":"Aug","3":"24","4":"3.0"},{"1":"Rainy","2":"Aug","3":"25","4":"2.8"},{"1":"Rainy","2":"Aug","3":"26","4":"2.5"},{"1":"Rainy","2":"Aug","3":"27","4":"2.7"},{"1":"Rainy","2":"Aug","3":"28","4":"2.3"},{"1":"Rainy","2":"Aug","3":"29","4":"2.5"},{"1":"Rainy","2":"Aug","3":"30","4":"3.3"},{"1":"Rainy","2":"Aug","3":"31","4":"3.9"},{"1":"Rainy","2":"Sep","3":"1","4":"3.1"},{"1":"Rainy","2":"Sep","3":"2","4":"4.1"},{"1":"Rainy","2":"Sep","3":"3","4":"2.8"},{"1":"Rainy","2":"Sep","3":"4","4":"3.2"},{"1":"Rainy","2":"Sep","3":"5","4":"3.1"},{"1":"Rainy","2":"Sep","3":"6","4":"4.1"},{"1":"Rainy","2":"Sep","3":"7","4":"3.2"},{"1":"Rainy","2":"Sep","3":"8","4":"4.1"},{"1":"Rainy","2":"Sep","3":"9","4":"4.5"},{"1":"Rainy","2":"Sep","3":"10","4":"2.9"},{"1":"Rainy","2":"Sep","3":"11","4":"2.4"},{"1":"Rainy","2":"Sep","3":"12","4":"2.7"},{"1":"Rainy","2":"Sep","3":"13","4":"2.9"},{"1":"Rainy","2":"Sep","3":"14","4":"3.2"},{"1":"Rainy","2":"Sep","3":"15","4":"2.2"},{"1":"Rainy","2":"Sep","3":"16","4":"2.7"},{"1":"Rainy","2":"Sep","3":"17","4":"3.3"},{"1":"Rainy","2":"Sep","3":"18","4":"3.5"},{"1":"Rainy","2":"Sep","3":"19","4":"3.1"},{"1":"Rainy","2":"Sep","3":"20","4":"4.4"},{"1":"Rainy","2":"Sep","3":"21","4":"3.0"},{"1":"Rainy","2":"Sep","3":"22","4":"3.3"},{"1":"Rainy","2":"Sep","3":"23","4":"3.6"},{"1":"Rainy","2":"Sep","3":"24","4":"3.5"},{"1":"Rainy","2":"Sep","3":"25","4":"3.8"},{"1":"Rainy","2":"Sep","3":"26","4":"3.9"},{"1":"Rainy","2":"Sep","3":"27","4":"3.3"},{"1":"Rainy","2":"Sep","3":"28","4":"3.2"},{"1":"Rainy","2":"Sep","3":"29","4":"1.7"},{"1":"Rainy","2":"Sep","3":"30","4":"2.6"},{"1":"Winter","2":"Oct","3":"1","4":"2.9"},{"1":"Winter","2":"Oct","3":"2","4":"2.7"},{"1":"Winter","2":"Oct","3":"3","4":"2.8"},{"1":"Winter","2":"Oct","3":"4","4":"2.4"},{"1":"Winter","2":"Oct","3":"5","4":"2.7"},{"1":"Winter","2":"Oct","3":"6","4":"3.0"},{"1":"Winter","2":"Oct","3":"7","4":"2.3"},{"1":"Winter","2":"Oct","3":"8","4":"3.5"},{"1":"Winter","2":"Oct","3":"9","4":"2.5"},{"1":"Winter","2":"Oct","3":"10","4":"2.6"},{"1":"Winter","2":"Oct","3":"11","4":"2.9"},{"1":"Winter","2":"Oct","3":"12","4":"3.1"},{"1":"Winter","2":"Oct","3":"13","4":"3.4"},{"1":"Winter","2":"Oct","3":"14","4":"3.1"},{"1":"Winter","2":"Oct","3":"15","4":"3.3"},{"1":"Winter","2":"Oct","3":"16","4":"2.4"},{"1":"Winter","2":"Oct","3":"17","4":"2.7"},{"1":"Winter","2":"Oct","3":"18","4":"3.0"},{"1":"Winter","2":"Oct","3":"19","4":"2.6"},{"1":"Winter","2":"Oct","3":"20","4":"2.1"},{"1":"Winter","2":"Oct","3":"21","4":"2.6"},{"1":"Winter","2":"Oct","3":"22","4":"3.0"},{"1":"Winter","2":"Oct","3":"23","4":"3.6"},{"1":"Winter","2":"Oct","3":"24","4":"2.9"},{"1":"Winter","2":"Oct","3":"25","4":"3.0"},{"1":"Winter","2":"Oct","3":"26","4":"2.8"},{"1":"Winter","2":"Oct","3":"27","4":"3.0"},{"1":"Winter","2":"Oct","3":"28","4":"3.8"},{"1":"Winter","2":"Oct","3":"29","4":"2.8"},{"1":"Winter","2":"Oct","3":"30","4":"3.1"},{"1":"Winter","2":"Oct","3":"31","4":"3.1"},{"1":"Winter","2":"Nov","3":"1","4":"3.1"},{"1":"Winter","2":"Nov","3":"2","4":"2.3"},{"1":"Winter","2":"Nov","3":"3","4":"1.8"},{"1":"Winter","2":"Nov","3":"4","4":"2.5"},{"1":"Winter","2":"Nov","3":"5","4":"2.8"},{"1":"Winter","2":"Nov","3":"6","4":"2.2"},{"1":"Winter","2":"Nov","3":"7","4":"3.0"},{"1":"Winter","2":"Nov","3":"8","4":"3.1"},{"1":"Winter","2":"Nov","3":"9","4":"2.8"},{"1":"Winter","2":"Nov","3":"10","4":"3.1"},{"1":"Winter","2":"Nov","3":"11","4":"2.4"},{"1":"Winter","2":"Nov","3":"12","4":"3.0"},{"1":"Winter","2":"Nov","3":"13","4":"2.1"},{"1":"Winter","2":"Nov","3":"14","4":"2.5"},{"1":"Winter","2":"Nov","3":"15","4":"2.6"},{"1":"Winter","2":"Nov","3":"16","4":"2.8"},{"1":"Winter","2":"Nov","3":"17","4":"3.0"},{"1":"Winter","2":"Nov","3":"18","4":"3.0"},{"1":"Winter","2":"Nov","3":"19","4":"3.1"},{"1":"Winter","2":"Nov","3":"20","4":"3.3"},{"1":"Winter","2":"Nov","3":"21","4":"2.3"},{"1":"Winter","2":"Nov","3":"22","4":"2.8"},{"1":"Winter","2":"Nov","3":"23","4":"2.2"},{"1":"Winter","2":"Nov","3":"24","4":"3.0"},{"1":"Winter","2":"Nov","3":"25","4":"2.5"},{"1":"Winter","2":"Nov","3":"26","4":"2.4"},{"1":"Winter","2":"Nov","3":"27","4":"2.3"},{"1":"Winter","2":"Nov","3":"28","4":"3.0"},{"1":"Winter","2":"Nov","3":"29","4":"2.6"},{"1":"Winter","2":"Nov","3":"30","4":"3.1"},{"1":"Winter","2":"Dec","3":"1","4":"3.3"},{"1":"Winter","2":"Dec","3":"2","4":"3.6"},{"1":"Winter","2":"Dec","3":"3","4":"2.9"},{"1":"Winter","2":"Dec","3":"4","4":"2.8"},{"1":"Winter","2":"Dec","3":"5","4":"2.1"},{"1":"Winter","2":"Dec","3":"6","4":"3.1"},{"1":"Winter","2":"Dec","3":"7","4":"3.1"},{"1":"Winter","2":"Dec","3":"8","4":"3.0"},{"1":"Winter","2":"Dec","3":"9","4":"2.2"},{"1":"Winter","2":"Dec","3":"10","4":"2.2"},{"1":"Winter","2":"Dec","3":"11","4":"2.4"},{"1":"Winter","2":"Dec","3":"12","4":"2.3"},{"1":"Winter","2":"Dec","3":"13","4":"2.0"},{"1":"Winter","2":"Dec","3":"14","4":"2.0"},{"1":"Winter","2":"Dec","3":"15","4":"3.1"},{"1":"Winter","2":"Dec","3":"16","4":"3.0"},{"1":"Winter","2":"Dec","3":"17","4":"2.5"},{"1":"Winter","2":"Dec","3":"18","4":"2.7"},{"1":"Winter","2":"Dec","3":"19","4":"2.5"},{"1":"Winter","2":"Dec","3":"20","4":"2.8"},{"1":"Winter","2":"Dec","3":"21","4":"2.6"},{"1":"Winter","2":"Dec","3":"22","4":"3.0"},{"1":"Winter","2":"Dec","3":"23","4":"3.0"},{"1":"Winter","2":"Dec","3":"24","4":"3.7"},{"1":"Winter","2":"Dec","3":"25","4":"3.2"},{"1":"Winter","2":"Dec","3":"26","4":"2.7"},{"1":"Winter","2":"Dec","3":"27","4":"2.7"},{"1":"Winter","2":"Dec","3":"28","4":"2.3"},{"1":"Winter","2":"Dec","3":"29","4":"2.6"},{"1":"Winter","2":"Dec","3":"30","4":"2.3"},{"1":"Winter","2":"Dec","3":"31","4":"2.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<hr />
<div id="summarise-of-the-dataset." class="section level3">
<h3>1.1 Summarise of the dataset.</h3>
<pre class="r"><code>summary(CS.temp)</code></pre>
<pre><code>##     Season             Month                Date      
##  Length:365         Length:365         Min.   : 1.00  
##  Class :character   Class :character   1st Qu.: 8.00  
##  Mode  :character   Mode  :character   Median :16.00  
##                                        Mean   :15.72  
##                                        3rd Qu.:23.00  
##                                        Max.   :31.00  
##   Temperature   
##  Min.   :1.700  
##  1st Qu.:2.700  
##  Median :3.000  
##  Mean   :3.002  
##  3rd Qu.:3.300  
##  Max.   :4.500</code></pre>
<hr />
</div>
<div id="transform-dtype." class="section level3">
<h3>1.2 Transform dtype.</h3>
<pre class="r"><code>CS.temp$Season = as.factor(CS.temp$Season)
CS.temp$Month = as.factor(CS.temp$Month)

# Summarise the dataset. 
summary(CS.temp)</code></pre>
<pre><code>##     Season        Month          Date        Temperature   
##  Rainy :122   Aug    : 31   Min.   : 1.00   Min.   :1.700  
##  Summer:120   Dec    : 31   1st Qu.: 8.00   1st Qu.:2.700  
##  Winter:123   Jan    : 31   Median :16.00   Median :3.000  
##               Jul    : 31   Mean   :15.72   Mean   :3.002  
##               Mar    : 31   3rd Qu.:23.00   3rd Qu.:3.300  
##               May    : 31   Max.   :31.00   Max.   :4.500  
##               (Other):179</code></pre>
<pre class="r"><code># Standard deviation.
sd(CS.temp$Temperature)</code></pre>
<pre><code>## [1] 0.4658319</code></pre>
<hr />
</div>
<div id="summarise-of-the-dataset-by-season-variable." class="section level3">
<h3>1.3 Summarise of the dataset by ‘Season’ variable.</h3>
<pre class="r"><code>CS.temp.summary.season = ddply(.data=CS.temp, .variable= ~ Season, .fun=function(data) summary(data$Temperature))
CS.temp.summary.season</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Season"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["Min."],"name":[2],"type":["dbl"],"align":["right"]},{"label":["1st Qu."],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Mean"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["3rd Qu."],"name":[6],"type":["dbl"],"align":["right"]},{"label":["Max."],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"Rainy","2":"1.7","3":"2.70","4":"3.05","5":"3.087705","6":"3.4","7":"4.5"},{"1":"Summer","2":"2.5","3":"2.90","4":"3.20","5":"3.147500","6":"3.4","7":"4.0"},{"1":"Winter","2":"1.8","3":"2.45","4":"2.80","5":"2.776423","6":"3.0","7":"3.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<hr />
</div>
<div id="check-the-detail-of-the-dataset." class="section level3">
<h3>1.4 Check the detail of the dataset.</h3>
<p><strong>The overview includes the following:</strong></p>
<ol style="list-style-type: decimal">
<li>Check the proportion of nulls.</li>
<li>Check if there’s any duplicated rows.</li>
</ol>
<pre class="r"><code>dataset_detail = function(df) {
    na_count = colSums(is.na(df))
    
    # Details. 
    nulls_proportion = na_count / nrow(df) * 100
    duplicated_nrows = nrow(which(duplicated(df)))
    
    details = list(nulls_proportion, duplicated_nrows)
    names(details) = c(&quot;nulls_proportion&quot;, &quot;duplicated_nrows&quot;)
    return(details)
}
    
CS.temp.details = dataset_detail(CS.temp)
CS.temp.details</code></pre>
<pre><code>## $nulls_proportion
##      Season       Month        Date Temperature 
##           0           0           0           0 
## 
## $duplicated_nrows
## NULL</code></pre>
<hr />
</div>
<div id="visualise-the-density-distribution-for-temperature-variable." class="section level3">
<h3>1.5 Visualise the density distribution for ‘Temperature’ variable.</h3>
<pre class="r"><code>ggplot(data=CS.temp) +
    aes(x=Temperature) +
    geom_density(fill=&quot;grey&quot;)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<hr />
</div>
<div id="visualise-the-distribution-for-temperature-variable-by-season." class="section level3">
<h3>1.6 Visualise the distribution for ‘Temperature’ variable by ‘Season’.</h3>
<pre class="r"><code>ggplot(data=CS.temp) +
    aes(x=Season, y=Temperature) +
    geom_boxplot() + 
    geom_hline(yintercept=4., color=&quot;red&quot;, alpha=.5) +
    geom_hline(yintercept=2., color=&quot;red&quot;, alpha=.5)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<hr />
</div>
<div id="visualise-the-density-distribution-for-temperature-variable-by-season." class="section level3">
<h3>1.7 Visualise the density distribution for ‘Temperature’ variable by ‘Season’.</h3>
<pre class="r"><code>ggplot(data=CS.temp) +
    aes(x=Temperature, fill=Season) +
    geom_density(alpha=.4)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<hr />
</div>
<div id="summary-for-section-1" class="section level3">
<h3>1.8 Summary for section 1:</h3>
<p><strong>Data dictionary:</strong></p>
<p>This dataset has 365 row. Each row refers to each date. The counts for each unique value of the <code>Season</code> variable is about 120 rows, which is quite balanced.</p>
<ol style="list-style-type: decimal">
<li><strong>Season:</strong> Rainy, Summer, Winter.</li>
<li><strong>Month:</strong> 1—12.</li>
<li><strong>Date:</strong> It refers to the day of the month.</li>
<li><strong>Temperature:</strong> <strong>Average milk temperature</strong> on that day.</li>
</ol>
<p><strong>Assumption on the dataset:</strong></p>
<p>The milk temperature is calculated based on average. Meaning even if one of the milk product’s temperature exceeds 2°C or 4°C, it will not considered a violation to the contract as long as the average is within 2—4°C.</p>
<p><strong>Findings from section 1.3:</strong></p>
<ol style="list-style-type: decimal">
<li>The dataset contains 3 independant variables and 1 dependent variable which is <code>Temperature</code>.</li>
<li><code>Date</code> is nested within <code>Month</code> variable, and <code>Month</code> variable is nested within <code>Season</code> variable.</li>
<li><code>Date</code> variable is not a fixed effect. It is a random effect nested within <code>Season</code> and <code>Month</code> variables.</li>
<li><code>Season</code> is a ‘between’ variable. <code>Month</code> is a ‘within’ variable.</li>
</ol>
<p><strong>Findings from section 1.4:</strong></p>
<ol style="list-style-type: decimal">
<li>The dataset has no null row.</li>
<li>The dataset has no duplicated row.</li>
</ol>
<p><strong>Findings from section 1.5, 1.6, and 1.7:</strong></p>
<ol style="list-style-type: decimal">
<li>The <code>Temperature</code> variable seems to be normally distributed on overall.</li>
<li>The <code>Temperature</code> for <code>Winter</code> and <code>Rainy</code> season is slighly right skewed.</li>
<li>The <code>Temperature</code> for <code>Summer</code> seems to be normally distributed.</li>
</ol>
<hr />
</div>
</div>
<div id="find-the-proportion-of-temperature-that-exceed-below-2c-and-above-4c." class="section level2">
<h2>2 Find the proportion of temperature that exceed below 2°C and above 4°C.</h2>
<pre class="r"><code># Proportion below 2°C.
temp.below.2 = sum(CS.temp$Temperature &lt; 2.0) / nrow(CS.temp)
temp.below.2</code></pre>
<pre><code>## [1] 0.008219178</code></pre>
<pre class="r"><code># Proportion above 4°C.
temp.above.4 = sum(CS.temp$Temperature &gt; 4.0) / nrow(CS.temp)
temp.above.4</code></pre>
<pre><code>## [1] 0.01917808</code></pre>
<pre class="r"><code># Total proportion that exceed the limits. 
temp.below.2 + temp.above.4</code></pre>
<pre><code>## [1] 0.02739726</code></pre>
<hr />
</div>
<div id="perform-one-way-anova-to-see-if-there-is-significant-difference-in-milk-temperature-between-different-seasons." class="section level2">
<h2>3 Perform One-way ANOVA to see if there is significant difference in milk temperature between different seasons.</h2>
<p><strong>Null hypothesis:</strong> mu(Rainy) = mu(Winter) = mu(Summer) <strong>Alternative hypothesis:</strong> At least 1 mean is different from the rest.</p>
<p><strong>Conditions for One-way ANOVA:</strong></p>
<ol style="list-style-type: decimal">
<li>Variance must be equal &gt;&gt; Do a Levene and Brown Forsythe test.</li>
<li>Data must normally distributed &gt;&gt; Do a Shapiro-Wilk and Anderson-Darling test + QQ plot.</li>
<li>Data must be non-paired.</li>
</ol>
<p>One-way ANOVA is robust to slight imbalance between the sample size of each season.</p>
<p><strong>Alternative methods to One-way ANOVA:</strong></p>
<ol style="list-style-type: decimal">
<li>The limit of ANOVA robustness to heterogeneity is 1.5 ratio between largest and smallest variance. If the variance is above 1.5 ratio, consider using Kruskal Wallis test or Welch ANOVA. Unequal variance will decrease power and therefore increases type 1 error. Here’s a reference to the article <a href="https://link.springer.com/article/10.3758/s13428-017-0918-2">Effect of variance ratio on ANOVA robustness: Might 1.5 be the limit?</a>.</li>
<li>If data is not normally distributed, consider using Box-Cox transformation. Otherwise, use Kruskal Wallis test.</li>
</ol>
<hr />
<div id="perform-an-assumption-test." class="section level3">
<h3>3.1 Perform an assumption test.</h3>
<div id="perform-levene-and-brown-forsythe-test-for-variance." class="section level4">
<h4>3.1.1 Perform Levene and Brown Forsythe test for variance.</h4>
<pre class="r"><code># Levene Test.
leveneTest(Temperature ~ Season, data=CS.temp, center=mean)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["F value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"8.049809","3":"0.0003797712","_rn_":"group"},{"1":"362","2":"NA","3":"NA","_rn_":""}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code># Brown Forsythe Test.
leveneTest(Temperature ~ Season, data=CS.temp, center=median)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["F value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"8.008439","3":"0.0003951169","_rn_":"group"},{"1":"362","2":"NA","3":"NA","_rn_":""}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<hr />
<div id="find-the-ratio-between-the-largest-and-smallest-variance." class="section level5">
<h5>3.1.1.1 Find the ratio between the largest and smallest variance.</h5>
<pre class="r"><code># Calculate variance for each season. 
var(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature)</code></pre>
<pre><code>## [1] 0.2779468</code></pre>
<pre class="r"><code>var(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature)</code></pre>
<pre><code>## [1] 0.1236912</code></pre>
<pre class="r"><code>var(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature)</code></pre>
<pre><code>## [1] 0.1716527</code></pre>
<pre class="r"><code># Calculate the ratio between largest and smallest variance. 
var(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature) / var(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature)</code></pre>
<pre><code>## [1] 2.247103</code></pre>
<hr />
</div>
</div>
<div id="perform-shapiro-wilk-and-anderson-darling-test." class="section level4">
<h4>3.1.2 Perform Shapiro-Wilk and Anderson-Darling test.</h4>
<pre class="r"><code># Perform normality test on temperature for &#39;Rainy&#39; season.
shapiro.test(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Rainy&quot;, ]$Temperature
## W = 0.98665, p-value = 0.2766</code></pre>
<pre class="r"><code># Perform normality test on temperature for &#39;Summer&#39; season.
shapiro.test(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Summer&quot;, ]$Temperature
## W = 0.97336, p-value = 0.01747</code></pre>
<pre class="r"><code># Perform normality test on temperature for &#39;Winter&#39; season.
shapiro.test(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Winter&quot;, ]$Temperature
## W = 0.98116, p-value = 0.08354</code></pre>
<pre class="r"><code># Perform normality test on temperature for &#39;Rainy&#39; season.
ad.test(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Rainy&quot;, ]$Temperature
## A = 0.63343, p-value = 0.09654</code></pre>
<pre class="r"><code># Perform normality test on temperature for &#39;Summer&#39; season.
ad.test(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Summer&quot;, ]$Temperature
## A = 0.80328, p-value = 0.03654</code></pre>
<pre class="r"><code># Perform normality test on temperature for &#39;Winter&#39; season.
ad.test(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature)</code></pre>
<pre><code>## 
##  Anderson-Darling normality test
## 
## data:  CS.temp[CS.temp$Season == &quot;Winter&quot;, ]$Temperature
## A = 0.77636, p-value = 0.04264</code></pre>
<hr />
</div>
<div id="visualise-the-normality-with-qq-plots." class="section level4">
<h4>3.1.3 Visualise the normality with QQ plots.</h4>
<pre class="r"><code>qqnorm(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature, pch=1, frame=FALSE)
qqline(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature, lwd=2)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre class="r"><code>qqnorm(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature, pch=1, frame=FALSE)
qqline(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature, lwd=2)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-18-2.png" width="672" /></p>
<pre class="r"><code>qqnorm(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature, pch=1, frame=FALSE)
qqline(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature, lwd=2)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-18-3.png" width="672" /></p>
<hr />
</div>
</div>
<div id="summary-for-section-3.1." class="section level3">
<h3>3.2 Summary for section 3.1.</h3>
<p><strong>Findings from 3.1.1:</strong></p>
<ol style="list-style-type: decimal">
<li>The data does fails the homogeneity test.</li>
<li>The variance ratio is larger than 1.5.</li>
</ol>
<p><strong>Findings from 3.1.2:</strong></p>
<ol style="list-style-type: decimal">
<li>The normality fails for temperature under <code>Summer</code> season.</li>
<li>The normality is near the borderline p-value for temperature under <code>Winter</code> season.</li>
</ol>
<p>This might be due to large sample size, larger sample size has higher the chance of detecting smaller difference. Looking at the plot from section 1.7, the data under summer (highlighted with green) looks somewhat symmetrical. The QQ plots also show that most of the data aren’t significantly diverted from the line. Hence, I will take it as near-normal.</p>
<p><strong>Next steps:</strong></p>
<p>I will do a Welch ANOVA test to address the unequal variance.</p>
<hr />
</div>
<div id="perform-anova-test." class="section level3">
<h3>3.3 Perform ANOVA test.</h3>
<div id="perform-welch-anova-test." class="section level4">
<h4>3.3.1 Perform Welch ANOVA test.</h4>
<p><strong>Null hypothesis:</strong> mu(Rainy) = mu(Summar) = mu(Winter) <strong>Alternative hypothesis:</strong> At least 1 mean is different from the rest.</p>
<pre class="r"><code>aov.result = oneway.test(formula=Temperature ~ Season, data=CS.temp, var.equal=FALSE)
aov.result</code></pre>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  Temperature and Season
## F = 29.959, num df = 2.00, denom df = 236.22, p-value =
## 2.537e-12</code></pre>
<hr />
</div>
<div id="perform-post-hoc-test-with-holm-bonferonni-correction." class="section level4">
<h4>3.3.2 Perform post-hoc test with Holm Bonferonni correction.</h4>
<pre class="r"><code># Perform pairwise comparison post-hoc test. 
ttest1 = t.test(CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature, 
                CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature, paired=FALSE, exact=TRUE, var.equal=FALSE, alternative=&#39;two.sided&#39;)
ttest2 = t.test(CS.temp[CS.temp$Season == &quot;Summer&quot;,]$Temperature, 
                CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature, paired=FALSE, exact=TRUE, var.equal=FALSE, alternative=&#39;two.sided&#39;)
ttest3 = t.test(CS.temp[CS.temp$Season == &quot;Winter&quot;,]$Temperature, 
                CS.temp[CS.temp$Season == &quot;Rainy&quot;,]$Temperature, paired=FALSE, exact=TRUE, var.equal=FALSE, alternative=&#39;two.sided&#39;)

# Apply Holm Bonferonni correction for p-value. 
p.adjust(c(ttest1$p.value, ttest2$p.value, ttest3$p.value), method=&quot;holm&quot;)</code></pre>
<pre><code>## [1] 2.997695e-01 3.128108e-12 1.200527e-06</code></pre>
<hr />
</div>
</div>
<div id="summary-for-section-3.3." class="section level3">
<h3>3.4 Summary for section 3.3.</h3>
<p><strong>Findings:</strong></p>
<ul>
<li>The Welch ANOVA show a significant difference for temperature between either season with a p-value below 0.001.</li>
<li>There is <strong>no significant difference</strong> for <strong>milk temperature between Rainy and Summer season</strong>. P-value = 0.299.</li>
<li>There is <strong>significant difference</strong> for <strong>milk temperature between Summer and Winter season</strong>. P-value = below 0.001.</li>
<li>There is <strong>significant difference</strong> for <strong>milk temperature between Rainy and Winter season</strong>. P-value = below 0.001.</li>
</ul>
<hr />
</div>
</div>
<div id="conclusion." class="section level2">
<h2>4 Conclusion.</h2>
<pre class="r"><code>ggplot(data=CS.temp) +
    aes(x=Season, y=Temperature) +
    geom_boxplot() + 
    geom_hline(yintercept=4., color=&quot;red&quot;, alpha=.5) +
    geom_hline(yintercept=2., color=&quot;red&quot;, alpha=.5)</code></pre>
<p><img src="investigating_the_cold_storage_milk_quality_maintenance_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<hr />
<p>Since there is a significant difference for milk temperature between each season, this means that there is <strong>at least 1 mean that is significantly different from the rest</strong>. This also means different season has different effect on the milk temperature. The <strong>post-hoc result</strong> shows that the <strong>average milk temperature</strong> for <strong>rainy and summer season</strong> is <strong>significantly different from winter season</strong>. Looking at the plot above, we can observe that rainy season has larger variation than summer and winter seasons and lowest control over the milk temperature. We can see that a small proportion of the temperature exceeds above 4°C and below 2°C. Additionally, there is also a small proportion of temperature that exceeds below 2°C during winter season, but the violation is mild compare to rainy season. Summer season has the highest control over milk temperature with fewer variation and no violation.</p>
<p>Hence, the company should find out the reason behind the cause, and be more cautious and prepared during winter and rainy season. Otherwise, Cold Storage can cease collaborating with the company and search for alternative company or solution.</p>
<hr />
</div>
<div id="notes-for-future-reference." class="section level2">
<h2>5 Notes for future reference.</h2>
<p>Latest update: <strong>2020/01/31</strong></p>
<p><strong>List of things to take note:</strong></p>
<ul>
<li>Currently none.</li>
</ul>
<p>—————————————————– END ——————————————————</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
